version: '3'

services:
  app:
    image: nginx:latest
    container_name: app
    hostname: app
    volumes:
      - ./data/app/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/app/index.php:/var/www/html/index.php
#    ports:
#     - 1088:1088

  php:
    image: php:fpm
    container_name: php
    hostname: php
    volumes:
      - ./data/app/index.php:/var/www/html/index.php

  proxy1:
    image: nginx:latest
    container_name: proxy1
    hostname: proxy1
    volumes:
      - ./data/proxy1/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1081:1081

  proxy2:
    image: nginx:latest
    container_name: proxy2
    hostname: proxy2
    volumes:
      - ./data/proxy2/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1082:1082

  proxy3:
    image: nginx:latest
    container_name: proxy3
    hostname: proxy3
    volumes:
      - ./data/proxy3/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1083:1083
